My Practise Programs

In [8]:
str1='Ravi Raj'

In [9]:
len(str1)

8

In [10]:
range(len(str1))

range(0, 8)

In [11]:
a=123214.243242

In [13]:
import math
math.ceil(a)

123215

In [14]:
math.floor(a)

123214

In [15]:
round(a)

123214

In [4]:
def check_palindrome(str1):
    str1=str1.lower()
    rev=str1[::-1]
    rev=rev.lower()
    if str1==rev:
        return True
    else:
        return False

check_palindrome('oohoo')
    

True

In [7]:
str2='Ravi'

In [8]:
str2[1:2]

'a'

In [19]:
str2[1:4]

'avi'

In [20]:
str2[:3]

'Rav'

In [21]:
str2[1:4:2]

'ai'

In [22]:
str2[:]

'RaviRaj'

In [23]:
str2[::]

'RaviRaj'

In [24]:
str2[-1:]

'j'

In [25]:
str2[::-1]

'jaRivaR'

In [26]:
Months_Dict={"January":1,"February":2,"March":3,"April":4,"May":5,"June":6,"July":7,"August":8,"September":9,"October":10,"November":11,"December":12}

In [27]:
Months_Dict

{'January': 1,
 'February': 2,
 'March': 3,
 'April': 4,
 'May': 5,
 'June': 6,
 'July': 7,
 'August': 8,
 'September': 9,
 'October': 10,
 'November': 11,
 'December': 12}

In [28]:
for i in Months_Dict.items():
    print(i)

('January', 1)
('February', 2)
('March', 3)
('April', 4)
('May', 5)
('June', 6)
('July', 7)
('August', 8)
('September', 9)
('October', 10)
('November', 11)
('December', 12)


In [31]:
for i,j in Months_Dict.items():
        print(i,j*100)

January 100
February 200
March 300
April 400
May 500
June 600
July 700
August 800
September 900
October 1000
November 1100
December 1200


In [39]:

def chk_pwd(str3):
    import re
    if re.search("(?!@#$%^&)",str3):
        print("Valid")
    else:
        print("Not Valid")

chk_pwd('Ravi')      

Valid


In [40]:
sentence='I love coding'

In [41]:
sentence.split()

['I', 'love', 'coding']

In [43]:
from collections import Counter
myList = [1,1,2,3,4,5,3,2,3,4,2,1,2,3]
Counter(myList)

Counter({1: 3, 2: 4, 3: 4, 4: 2, 5: 1})

In [44]:
dict1={'FirstName':[],'LastName':[],'Zipcode':[]}
dict1['FirstName'].append('Ravi Raj','Akhilesh','Venkatesh')
dict1['LastName'].append('Chenna','Kotla','Idiyala')
dict1['Zipcode'].append(14214,14213,14215)

TypeError: append() takes exactly one argument (3 given)

In [45]:
dict1['FirstName'].append('Ravi Raj')
dict1['LastName'].append('Chenna')
dict1['Zipcode'].append(14214)

In [46]:
dict1

{'FirstName': ['Ravi Raj'], 'LastName': ['Chenna'], 'Zipcode': [14214]}

In [50]:
a=input('Enter a number: ')
def add():
    return int(a)+12
a=add()
print(a)

Enter a number: 2
14


In [53]:
def reverseAString(str1):
    #str1=str1.lower()
    output=""
    for i in str1:
        print(i)
        output=i+output
    return output

reverseAString('Ravi')

R
a
v
i


'ivaR'

In [56]:
def reverseANumber(number):
    reversed_num=0
    while number!=0:
        digit = number % 10
        #print(digit) 4 3
        reversed_num = reversed_num * 10 + digit
        #print(reversed_num) 4 43
        number //= 10
        #print(number) 123 12
    return reversed_num

reverseANumber(1234)

4
4
123
3
43
12
2
432
1
1
4321
0


4321

In [77]:
listre=[1,43,65,231,21,56,89,43,11]

In [85]:
listre.sort()
print(listre)

[1, 11, 21, 43, 43, 56, 65, 89, 231]


In [154]:
b=[1,9,5,4,7,8]
b.sort()

In [155]:
b

[1, 4, 5, 7, 8, 9]

In [84]:
prime_numbers = [11, 3, 7, 5, 2]

# sorting the list in ascending order
prime_numbers.sort()

print(prime_numbers)

[2, 3, 5, 7, 11]


In [86]:
prime_numbers = [11, 3, 7, 5, 2]


In [87]:
sorted(prime_numbers)

[2, 3, 5, 7, 11]

In [88]:
prime_numbers

[11, 3, 7, 5, 2]

In [91]:
prime_numbers.sort(reverse=True)

In [92]:
prime_numbers

[11, 7, 5, 3, 2]

In [152]:
list1=[2,4,6,8,10]
list2=list(map(lambda a:a*2,list1))
list2

[4, 8, 12, 16, 20]

In [ ]:
list(map(lambda n: n * 2, [1, 2, 3, 4, 5]))

In [ ]:
(lambda x: x + 1)(2

In [60]:
    n = int(input())
    arr = map(int, input().split())
    print(arr[1])

5
1 2 3 4 5


TypeError: 'map' object is not subscriptable

In [94]:
for i in range(6):
    print('Hello')

Hello
Hello
Hello
Hello
Hello
Hello


In [95]:
a=0
b=1
list1=[a,b]
for i in range(10):
    c=a+b
    list1.append(c)
    a=b
    b=c
print(list1)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


In [101]:
list1 = ["The Matrix", "The Matrix Reloaded", "The Matrix Revolutions", "The Matrix Resurrections"]
l=len(list1)
print("l is: ", l)
for i in range(int(l/2)):
    n=list1[i]
    #print(" n is: ",n)
    list1[i]=list1[l-i-1] #list1[4-0-1]=list1[3], 
    #print("list1[l-i-1]=",list1[l-i-1])
    #print("list1[i]= ",list1[i])
    list1[l-i-1]=n
    #print("list1[l-i-1]=",list1[l-i-1])
print(list1)

l is:  4
 n is:  The Matrix
list1[l-i-1]= The Matrix Resurrections
list1[i]=  The Matrix Resurrections
list1[l-i-1]= The Matrix
 n is:  The Matrix Reloaded
list1[l-i-1]= The Matrix Revolutions
list1[i]=  The Matrix Revolutions
list1[l-i-1]= The Matrix Reloaded
['The Matrix Resurrections', 'The Matrix Revolutions', 'The Matrix Reloaded', 'The Matrix']


In [102]:
print(range(2))

range(0, 2)


In [103]:
for i in range(2):
    print(i)

0
1


In [104]:
researchers = ['Yann LeCun', 'Yoshua Bengio', 'Geoffrey Hinton', 'Fei-Fei Li', 'Andrew Ng']

for i,j in enumerate(researchers):
    print(i,j)

0 Yann LeCun
1 Yoshua Bengio
2 Geoffrey Hinton
3 Fei-Fei Li
4 Andrew Ng


In [105]:
researchers = ['Yann LeCun', 'Yoshua Bengio', 'Geoffrey Hinton', 'Fei-Fei Li', 'Andrew Ng']
work = ['Facebook', 'Université de Montréal', 'University of Toronto', 'Stanford University', 'Landing AI']

res=zip(researchers,work)

In [106]:
res

In [107]:
print(res)

In [108]:
list(res)

[('Yann LeCun', 'Facebook'),
 ('Yoshua Bengio', 'Université de Montréal'),
 ('Geoffrey Hinton', 'University of Toronto'),
 ('Fei-Fei Li', 'Stanford University'),
 ('Andrew Ng', 'Landing AI')]

In [109]:
import numpy as np

In [116]:
array1=np.random.randint(1,50,size=14)
print(array1)

[ 7 27 26 43 20 22 27 10 40 41 36 12 36 22]


In [117]:
array1[1:]

array([27, 26, 43, 20, 22, 27, 10, 40, 41, 36, 12, 36, 22])

In [118]:
array1

array([ 7, 27, 26, 43, 20, 22, 27, 10, 40, 41, 36, 12, 36, 22])

In [123]:
arr2=np.array_split(array1,4)
arr2

[array([ 7, 27, 26, 43]),
 array([20, 22, 27, 10]),
 array([40, 41, 36]),
 array([12, 36, 22])]

In [124]:
def listw(list1):
    oplist=[]
    for i in list1:
        if i%3==0 or i%4==0:
            oplist.append(i)
    return oplist


In [125]:
listw([1,2,3,4,5,6,7,8,9,10])

[3, 4, 6, 8, 9]

In [129]:
 arr3=np.reshape(listw,-1)

In [130]:
arr3

array([<function listw at 0x7fa5b95ba0d0>], dtype=object)

In [136]:
a=0
b=1
lst=[a,b]
for i in range(1,24):
    c=a+b
    lst.append(c)
    a=b
    b=c
print(lst)


[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368]


In [137]:
len(lst)

25

In [ ]:
def checkFib(num):
    a=0
    b=1
    lst=[a,b]
    for i in range(1,24):
        c=a+b
        lst.append(c)
        a=b
        b=c
    print(lst)

In [145]:
def firstWord(word):
    if word=='':
        return ''
    else:
        op=word.lower().split()
        op.sort()
        for i in op:
            print(i)
    
    

In [146]:
firstWord('My name is Apple')

apple
is
my
name


In [156]:
a=input('How are you doing?')
print(a)

How are you doing?I am fine
I am fine


In [157]:
mylist = ["Green","Green", "Red", "Yello",1,1,2,3,4,True,False]

In [160]:
list(set(mylist))

[False, 1, 2, 3, 4, 'Green', 'Red', 'Yello']

In [161]:
tuple1=(1,2,2,3,3,4)

In [162]:
tuple1[2]=99999

TypeError: 'tuple' object does not support item assignment

In [163]:
mylist[3]="pinky red"

In [164]:
mylist

['Green', 'Green', 'Red', 'pinky red', 1, 1, 2, 3, 4, True, False]

In [166]:
set1={1,2,3,4,432,4,4,4,4,2,2,2,1,1,1}

In [167]:
set1

{1, 2, 3, 4, 432}

In [168]:
set1[2]=9999

TypeError: 'set' object does not support item assignment

In [2]:
n = int(input())
arr = map(int, input().split())

5
1 2 3 4 5


In [4]:
n = int(input())
arr = map(int, input().split())
    
res=list(arr)
res.remove(max(res))
print(max(res))

4
22 54534 65476587654 213
54534


In [7]:
res=[1,6,2,4,6]
res.sort()
for i in range(len(res)):
    if i==max(res):
        res.remove(i)
        i=i+1
print(max(res))

6


In [8]:
def second_largest(list):
    large= max(list)
    list.remove(large)
    large= max(list)
    return large

In [9]:
second_largest([1,6,2,4,6])

6

In [18]:
res=[2,6,6,3]
maximum=max(res)
for i in res:
    if i==maximum:
        res.remove(i)
        maximum=max(res)
print(maximum)

6


In [15]:
    n = int(input())
    arr = map(int, input().split())
    
    res=list(arr)
    maximum=max(res)
    for i in res:
        if i==maximum:
            res.remove(i)
            maximum=max(res)
            
            
    print(maximum)

4
2 6 6 3
6


In [25]:
res=[2,6,6,3]
set1=set(res)
lst=list(set1)
maximum=max(lst)
for i in lst:
    if i==maximum:
        lst.remove(i)
        maximum=max(lst)
print(maximum)


3


In [22]:
res=[2,6,6,3]
set1=set(res)
set1

{2, 3, 6}

In [23]:
lst=list(set1)

In [24]:
lst

[2, 3, 6]

In [26]:
for _ in range(int(input())):
        name = input()
        score = float(input())

2 4 5 6 7


ValueError: invalid literal for int() with base 10: '2 4 5 6 7'

In [27]:
for _ in range(int(input())):
        name = input()
        score = float(input())

4
ravi raj jon snow
12.2 43.5 21.9 67


ValueError: could not convert string to float: '12.2 43.5 21.9 67'